### ISSUE TITLE
Behind the proxy

### ISSUE THREAD

**Issue by swatikurra17** [GanadiniAkshay/weatherBot#3]
Hi Akshay, 

This piece of code work doesn't work behind the proxy. I am no able to hit api.ai API using this code. 
Please suggest what setting needs to be done for this . 
I have already **proxy** and **http-proxy** variables set in he npm config.

**Comment by GanadiniAkshay** [comment]
I am not sure what you mean by behind the proxy? Can you provide more details

**Comment by swatikurra17** [comment]
Actually due to firewall restrictions, we can't directly access api.ai. So, i have set up a proxy and trying to make to call to api through proxy but still getting this error - 
Error: Request to 'http://<localhost:portnumber>/v3/botstate/emulator/users/default-use
r' failed: [400] Bad Request

**Comment by GanadiniAkshay** [comment]
Oh okay that looks like its trying to connect to the bot connector through the proxy which isn't working. This is more of an issue on microsoft bot framework than from this library.
